theme: jekyll-theme-midnight
title: Notes for CSC3022H
description: These notes are aligned to questions in previous exams and aim to comprehensively cover the content needed to answer these questions.
